---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Make Nginx config
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
