---
- name: Install apt-transport-https
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - software-properties-common

- name: Add php repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes

- name: Install php
  ansible.builtin.apt:
    pkg:
      - php7.3
      - php7.3-common
      - php7.3-fpm
      - php7.3-bcmath
      - php7.3-curl
      - php7.3-gd
      - php7.3-json
      - php7.3-mbstring
      - php7.3-mysql
      - php7.3-geoip
      - php7.3-xml
      - php7.3-zip
      - php7.3-redis
    state: latest
