---
- name: Add php repository
  ansible.builtin.command: add-apt-repository ppa:ondrej/php -y

- name: Install php
  ansible.builtin.apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-common
      - php{{ php_version }}-fpm
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-json
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-mysql
      - php{{ php_version }}-geoip
      - php{{ php_version }}-yaml
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-redis
  notify: restart php-fpm
