---
- name: Add php repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes

- name: Install php
  ansible.builtin.apt:
    pkg:
      - php{{ php_version }}
      - php{{ php_version }}-common
      - php{{ php_version }}-fpm
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-json
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-mysql
      - php{{ php_version }}-geoip
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-redis
    state: latest
