---
- hosts: localhost
  connection: local
  become: true
  vars:
    php_version: 7.4
    composer_version: 2.8.3
    deployer_version: 6.9.0
  roles:
    - common
    - nginx
    - php-fpm
    - composer
    - deployer
