---
- name: "install packages"
  ansible.builtin.apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 3600

- name: "install packages"
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ packages }}"
