---
- name: Install php composer
  ansible.builtin.get_url:
    url: https://github.com/composer/composer/releases/download/{{ composer_version }}/composer.phar
    dest: /usr/local/bin/composer
    mode: +x
