---
- name: Set a hostname
  ansible.builtin.hostname:
    name: test.dev.cloud

- name: Dafault packages
  ansible.builtin.apt:
    name:
      - git
      - wget
      - awscli
      - unzip
      - mysql-client
