---
- name: Set a hostname
  ansible.builtin.hostname:
    name: test.dev.cloud

- name: Custom profile
  ansible.builtin.copy:
    src: custom-profile.sh
    dest: /etc/profile.d/custom.sh

- name: Dafault packages
  ansible.builtin.apt:
    name:
      - git
      - wget
      - awscli
      - unzip
      - mysql-client
      - software-properties-common
      - apt-transport-https
